### ISSUE TITLE
JSON Schema integration (feature request)

### ISSUE THREAD

**Issue by nmorse** [daffl/jquery.dform#12]
Link to or embed a "JSON Schema".  To be used for a unified source of information on the types of properties, and other qualifying meta data.

**Comment by kokujin** [comment]
Hi there, is this still viable? I would like to use JSON Schema objects to generate forms

**Comment by daffl** [comment]
There is an old start for a JSON schema converter here: https://github.com/daffl/jquery.dform/blob/master/src/dform.converters.js#L71. It still needs some work and someone to take it on though.

**Comment by kokujin** [comment]
Nice @daffl , is the usage of converters documented somewhere? I could give it a try. Any list on what is missing from your implementation?
