### ISSUE TITLE
Dynamic label links

### ISSUE THREAD

**Issue by lahdekorpi** [daffl/jquery.dform#51]
Labels don't automatically have a "for" attribute when generated, so they aren't linked to any element.
This means that when the user clicks a label, input isn't focused.
Same goes with accessibility, screen readers don't know what label belongs to what element.

Would auto-generating id's for each element be possible?

**Comment by daffl** [comment]
It might be. We could just add a type that generates an id based on the name (if there is no id).
Labels should be already linked when you give your input field an id explicitly though.

**Comment by lahdekorpi** [comment]
Yes, those ones (like the username field on the first demo) work just fine.
I've had similar situations where the id's needed to generated dynamically.

The one thing to take into account is that they need to be unique on the whole document and we can't be sure about what id's are already present on the DOM nor what are being generated by other scripts.
Also, if there are multiple dform generated ones...

So a namespace id="dform-{{name}}-{{i}}" with a global counter could work?
