### ISSUE TITLE
How to make different name of checkbox?

### ISSUE THREAD

**Issue by ND17** [daffl/jquery.dform#52]
{
                    "type":"checkboxes",
                    "name":"color",
                    "options":{
                        "blue" : {
                            "value":"blue",
                             "caption":{
								"html" : "Blue",
								"css" : {
									"display" : "inline"
									
								}
							},
							"css" : {
								"display" : "inline"
							}
                        },
						"red" :  {
                            "value":"red",
                            "caption":{
								"html" : "Red",
								"css" : {
									"display" : "inline"
									
								}
							},
							"css" : {
								"display" : "inline"
							}
                        },
						"black" :  {
                            "value":"black",
                            "caption":{
								"html" : "Black",
								"css" : {
									"display" : "inline"
									
								}
							},
							"css" : {
								"display" : "inline"
							}
                        }
					}
                    
				
This code generates

              <div class="ui-dform-checkboxes">
                   <input type="checkbox" class="ui-dform-checkbox" value="blue" name="color" style="display: inline;">
                   <label class="ui-dform-label" style="display: inline;">Blue</label>
                   <input type="checkbox" class="ui-dform-checkbox" value="red" name="color" style="display: inline;">
                  <label class="ui-dform-label" style="display: inline;">Red</label>
                  <input type="checkbox" class="ui-dform-checkbox" value="black" name="color" style="display: inline;">
                  <label class="ui-dform-label" style="display: inline;">Black</label>
         </div>

I want to add different name of all checkbox. 

like this

              <input type="checkbox" class="ui-dform-checkbox" value="blue" name="colorblue" style="display: inline;">
              <input type="checkbox" class="ui-dform-checkbox" value="blue" name="colorred" style="display: inline;">
              <input type="checkbox" class="ui-dform-checkbox" value="blue" name="colorblack" style="display: inline;">

how can i do this using dform?

**Comment by daffl** [comment]
I would probably create the checkbox list manually via individual checkbox elements (instead of the `checkboxes` type). The idea for checkboxes was to always have the same name.

```js
{
  "type":"div",
  "html":[{
    "type": "checkbox",
    "value":"blue",
    "name": "colorblue",
    "caption":{
      "html" : "Blue",
      "css" : { "display" : "inline" }
    }
    // ...
    ]
}
```
