### ISSUE TITLE
When using with AngularJS Submit button does not do anything

### ISSUE THREAD

**Issue by abku** [daffl/jquery.dform#55]
When using dform with AngularJS website, when the submit button is clicked the form does not submit.

**Comment by daffl** [comment]
It would be easier with a [JSBin](http://jsbin.com) example but my guess is that Angular does not run non-Angular dynamically inserted HTML.

**Comment by abku** [comment]
Can we setup so that submit calls a Javascript function to submit?  We can always load the function in the controller so that AngularJS recognizes it.
