### ISSUE TITLE
It seems the validation is not working...

### ISSUE THREAD

**Issue by winsonet** [daffl/jquery.dform#57]
I tried to use the validation, but it doesn't work, you can try in here:

http://jsfiddle.net/out4veth/4/

when I click the login button, the form is submit and there is no any validation :(

I am using this jquery validation plugin, should be the same with yours, right?

https://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.js

the website:

http://jqueryvalidation.org/

**Comment by winsonet** [comment]
when I try in my localhost, I got the below error when submit the form:

```
Uncaught TypeError: Cannot read property 'length' of undefinedn.extend.map 
@ jquery-2.1.4.min.js:2$.extend.check 
@ jquery.validate.js:728$.extend.checkForm 
@ jquery.validate.js:445$.extend.form 
@ jquery.validate.js:432(anonymous function) 
@ jquery.validate.js:99n.event.dispatch 
@ jquery-2.1.4.min.js:3r.handle 
@ jquery-2.1.4.min.js:3
```

**Comment by winsonet** [comment]
sorry, I have solved the problem, I forgot to set the element's name, so the validation is not working...
you can close the issue.

**Comment by daffl** [comment]
Glad you figured it out. Odd, I thought you should be able to close the issue, too.
