### ISSUE TITLE
How can I don't use the 'form' tag?

### ISSUE THREAD

**Issue by winsonet** [daffl/jquery.dform#58]
I want to handle the form tag by myself, for my case, I need to dynamic generate the form elements within difference tabs(these tabs are dynamic generate from backend), because these data are from backend programming, so I don't want to use the build-in tab function in dform, for example, my html code:

```
<form id="myform" action="#">
<tab id=1>
       //call dform to generate the form elements
</tab>
<tab id=2>
       //call dform to generate the form elements
</tab>
...
</form>
```

but the dform function will always generate the form tag(for my case, there will be many of form tag in the page), so I can't use my global form tag to handle the submit event. 

Any ideas for this case?

Thanks!

**Comment by daffl** [comment]
It won't create the form it you pass a `type` in the root element. For example, to add a paragraph to tab `#2` you can do:

```js
$('#2').dform({
  type: 'p',
  html: 'This is a paragraph'
});
```

**Comment by winsonet** [comment]
oh, that's great!!

Thanks!!
