### ISSUE TITLE
IE8 dform not supported

### ISSUE THREAD

**Issue by edrakitin** [daffl/jquery.dform#61]
Hello. 
I have some troubles with my MVC 4 Razor application.
This is my test code - 

```
<div class="span8">
        <h2 style="margin-bottom: 20px;">Answer</h2>
        <form id="sendForm"></form>
   `</div>`
```

$(document).ready(function () {
$("#sendForm").dform({
                type : "span",
                id : "the-span",
                text : "Test"
            });
});
When I start app at >=IE9 all works fine.
But if i use IE8 i get this error - 
Object not supported property or method "dform".
I have read all the available sources, tried everything - unfortunately nothing was helped.
What I am doing wrong?

**Comment by hectorarguello** [comment]
Hi,
I was really optimistic about using this converter, but one of the requisites of the web app was that it must work with IE8. What a bummer. Hope I could make use of this in the future.

**Comment by daffl** [comment]
IE8 has reached its end of life almost two years ago, I don't think this issue will be addressed anymore unfortunately.
