### ISSUE TITLE
non-obvious how to implement ajax subscriber

### ISSUE THREAD

**Issue by rob-lindman** [daffl/jquery.dform#63]
I am attempting to use the ajax subscriber with dform. 

it's unclear how to leverage this.

I would like to be able to load the json over ajax and specify where to direct the response / handle the response based on status code / error messages returned.

perhaps you can add some documentation of an example. I am not sure how to format the json to use the ajax.  

otherwise this is an extremely interesting and useful tool.

**Comment by daffl** [comment]
You create elements loaded from remote JSON with the `url` subscriber

```js
{
    "type" : "div",
    "url": "form.json"
}
```

or initialize a complete form with remote JSON with `$(form).dform('ajax', params [, success] [, error])`

**Comment by rob-lindman** [comment]
still not seeing how to put this all together... is it something like this...

$(form).dform('ajax', 
array(
{
    "type" : "div",
    "url": "form.json"
}
)
 , successCallback, errorCallback);

**Comment by daffl** [comment]
```js
$(form).dform('ajax', {
  dataType: 'json',
  url: 'form.json'
});
```

Or in a form definition:

```js
$(form).dform({
  type: 'div',
  html: {
   type: 'p',
   url: 'paragraph-content.json'
  }
});
```

**Comment by rob-lindman** [comment]
We're not talking about the same thing here, and I'm trying to figure out how to communicate it, so please forgive me if I err.

I am trying to access the functionality that is in the extensions, to use the ajaxForm plugin:

	$.dform.subscribe("ajax",
		/**
		 * If the current element is a form, it will be turned into a dynamic form
		 * that can be submitted asynchronously.
		 *
		 * @param options Options as specified in the [jQuery Form plugin documentation](http://jquery.malsup.com/form/#options-object)
		 * @param type The type of the element
		 */
		function(options, type)
		{
			if(type === "form")
			{
				this.ajaxForm(options);
			}
		}, $.isFunction($.fn.ajaxForm));

I tried the code below, which does load and display the form definition. What it does not do is use the above code in order to activate the ajaxForm functionality.
		
	$("#ajax-test").dform('ajax', '/apps/core/f-test.json', function(data) {
      //    this //-> Generated $('#myform')
      //    data //-> data from path/to/form.json
		alert('something');
      }


What I want to do is specify the URL and the callback functions for the ajaxForm callback using the subscriber above.... Load the form definition from json, add the ajaxform options, and specify the URL, and then I have the end result I am looking for...

```
``
$(document).ready ...

var type = "form";

var options = { 
    target:     '#divToUpdate', 
    url:        'comment.php', 
    success:    function() { 
        alert('Thanks for your comment!'); 
    } 
}; 

// somehow call the dform plugin with the ajax load of the json
// somehow attach the options for ajaxForm and trigger the ajaxForm on it.

	$("#ajax-test").dform('ajax', '/apps/core/f-test.json', function(data) {
		alert('something');
      }
```

I am not sure if I am explaining this perfectly but this should allow you to sort of narrow in on what I mean. 

Does this make sense? 

I guess what I am basically asking is how to properly assign the options for that subscriber in the top of this post.

Thanks.
