### ISSUE TITLE
Custom select not inserting options

### ISSUE THREAD

**Issue by Bjern** [daffl/jquery.dform#67]
Hi

I know this is an old project but so useful today still.  I am having some trouble getting options `<options>` into my select `<select>`.  I am using some dynamic code to get the options from a device db and insert them into the select.  However no matter what I do the tag comes up empty.

Code below:

```javascript
 
    // Select / dropdown using existing stored data
    $.dform.addType('object_select', function (data) {

    var str = data.name;
    var opts = {};

     // get the data for this object
     select_options = app_db.get('app_data_schema', str).done(function (results) {

    // iterate through the options
                $.each(results.object_data, function (key, record) {

                    var id, name;

                    // check for a possible key value
                    $.each(record, function (r_key, r_record) {

                        // becareful this assumes you only have one key with an _id on the end.
                        if (r_key.match('_id$')) {
                            id = r_record;
                        }

                        if (r_key.match('name')) {
                            name = r_record;
                        }

                    });

                    if ((id !== null && id !== undefined) && (name !== null && name !== undefined)) {
                        opts['"' + id + '"'] = name;
                    }

                });
                data.options = opts;
                data.type = 'select';
                data.html = 'hello';

            });
            console.log(data);
            return $("<select>").dform('attr', data).html('');

        });

```
Result:
```
<select name="remark_name" id="remark_name" class="ui-dform-object_select selectpicker bs-select-hidden form-control"></select>
```

The console give me the right details it seems:
```
{name: "remark_name", id: "remark_name", caption: "Remedy", class: "selectpicker bs-select-hidden form-control"}
caption : "Remedy"
class : "selectpicker bs-select-hidden form-control"
html : "hello"
id : "remark_name"
name : "remark_name"
options : {"4195730": "Baycidal SC", "4195734": "Baythroid Wettable Powder", "4195738": "Bayticol Aerosol" 
```
... you get the idea.

As you can see above the select result is empty.
![2018-06-01 10_39_22-identic - microsoft visual studio](https://user-images.githubusercontent.com/2159224/40830992-22b05d8e-6588-11e8-8c88-ec7d7539b3c6.png)

OMG I cant get the markdown to work!!

**Comment by tobya** [comment]
Please format your question, its very difficult to read.

**Comment by Bjern** [comment]
I really tried to use the markdown but its not working. in Edit it is formatted.  Stupid github editor markdown rubbish.  If it take a snapshot and insert the picture you can see it better.

![2018-06-01 21_50_42-custom select not inserting options issue 67 daffl_jquery dform](https://user-images.githubusercontent.com/2159224/40860513-e7c51148-65e5-11e8-8c84-31580f16fa9f.png)

![2018-06-01 21_52_01-custom select not inserting options issue 67 daffl_jquery dform](https://user-images.githubusercontent.com/2159224/40860558-190aed72-65e6-11e8-8774-7a2a94dab905.png)

**Comment by Bjern** [comment]
If you can help it would be appreciated.  Just ranting since I have been struggling with this for a while now. Tx

**Comment by tobya** [comment]
what debugging have you done?  What do you get if you output 

- `console.log(results)`
- `console.log(record)`

**Comment by Bjern** [comment]
Thanks for your help.  Attached are screens of the debug results on "data".  You will see that the options have been included in the json being sent to dform.  The select control is perfectly generated BUT the options are never inserted.

![2018-06-05 10_24_19-identic](https://user-images.githubusercontent.com/2159224/40964167-b012a81a-68aa-11e8-8246-f5bc2ac057b4.png)

![2018-06-05 10_13_03-identic](https://user-images.githubusercontent.com/2159224/40963653-73562696-68a9-11e8-8bd8-277f8313912f.png)

What I based this off...

![2018-06-05 10_25_30](https://user-images.githubusercontent.com/2159224/40964246-e1a046b2-68aa-11e8-9a0c-6465bda4f729.png)

**Comment by Bjern** [comment]
After some debugging and much frustration it turns out this is a javascript scope thing.  The variable can be seen in all the functions travelling down the code as it is a global.  However you cannot set it as you return back despite it being global.  Its a stupid javascript thing as usual.

Tx for trying to assist.
